# Generated by Django 5.2.5 on 2025-08-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_first_name', models.CharField(max_length=254)),
                ('client_last_name', models.CharField(max_length=254)),
                ('client_address', models.CharField(max_length=254)),
                ('client_phone', models.CharField(max_length=11)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_create_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
