# Generated by Django 5.2.5 on 2025-08-30 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_reciver', models.CharField()),
                ('transaction_sender', models.CharField()),
                ('transaction_date', models.DateField()),
                ('transaction_amount', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards_date', models.DateField(auto_created=True)),
                ('cards_numbers', models.CharField(max_length=16)),
                ('cards_exp', models.DateField()),
                ('cards_full_name', models.CharField(max_length=508)),
                ('cards_cvv', models.CharField(max_length=3)),
                ('cards_amount', models.BigIntegerField()),
                ('cards_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.clients')),
            ],
        ),
    ]
